# Generated by Django 4.2.7 on 2025-06-25 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "steam_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Steam ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="游戏名称")),
                ("description", models.TextField(blank=True, verbose_name="游戏描述")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="价格",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=10, verbose_name="货币"),
                ),
                (
                    "discount_percent",
                    models.IntegerField(default=0, verbose_name="折扣百分比"),
                ),
                ("header_image", models.URLField(blank=True, verbose_name="头图链接")),
                (
                    "screenshots",
                    models.JSONField(blank=True, default=list, verbose_name="截图列表"),
                ),
                (
                    "developer",
                    models.CharField(blank=True, max_length=200, verbose_name="开发商"),
                ),
                (
                    "publisher",
                    models.CharField(blank=True, max_length=200, verbose_name="发行商"),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="发布日期"),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "review_score",
                    models.IntegerField(blank=True, null=True, verbose_name="评分"),
                ),
                ("review_count", models.IntegerField(default=0, verbose_name="评论数量")),
                (
                    "platforms",
                    models.JSONField(blank=True, default=list, verbose_name="支持平台"),
                ),
                (
                    "languages",
                    models.JSONField(blank=True, default=list, verbose_name="支持语言"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="抓取时间"
                    ),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="是否免费")),
                ("is_new", models.BooleanField(default=True, verbose_name="是否新游戏")),
            ],
            options={
                "verbose_name": "游戏",
                "verbose_name_plural": "游戏",
                "db_table": "games",
                "ordering": ["-scraped_at", "-created_at"],
            },
        ),
    ]
