"""
Import command to ingest legacy CSV exports into the Django models.
"""

from __future__ import annotations

import csv
from datetime import datetime, date
from pathlib import Path
from typing import Any

import requests
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone

from core import models
from core.nsfw import classify_nsfw_from_row


class Command(BaseCommand):
    help = "Import a CSV file generated by steam_daily.py into the Django database."

    def add_arguments(self, parser):
        parser.add_argument("csv_path", help="Path to the CSV file to ingest.")
        parser.add_argument(
            "--source-name",
            default="steam_daily",
            help="Identifier for the crawler that produced the CSV.",
        )
        parser.add_argument(
            "--ingested-date",
            dest="ingested_date",
            help="Business date for this import (YYYY-MM-DD). Defaults to file stem or today.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse and log actions without writing to the database.",
        )

    def handle(self, *args, **options):
        self._asset_cache: dict[int, dict[str, str]] = {}
        csv_path = Path(options["csv_path"]).expanduser()
        if not csv_path.exists():
            raise CommandError(f"CSV file not found: {csv_path}")

        ingested_date = self._resolve_ingested_date(csv_path, options.get("ingested_date"))
        source_name = options["source_name"]
        dry_run = options["dry_run"]

        self.stdout.write(f"Importing {csv_path} for {ingested_date} (source: {source_name})")

        with csv_path.open("r", encoding="utf-8-sig") as fh:
            reader = csv.DictReader(fh)
            rows = list(reader)

        if not rows:
            self.stdout.write(self.style.WARNING("No rows detected, nothing to do."))
            return

        if dry_run:
            self.stdout.write(f"[dry-run] Would process {len(rows)} rows.")
            return

        with transaction.atomic():
            batch = models.DiscoveryBatch.objects.create(
                source_name=source_name,
                run_started_at=timezone.now(),
                ingested_for_date=ingested_date,
                source_file=str(csv_path),
                parameters={"fieldnames": reader.fieldnames},
            )
            processed_count, skipped_nsfw = self._ingest_rows(batch, rows)
            batch.run_completed_at = timezone.now()
            batch.save(update_fields=["run_completed_at"])

        message = f"Ingested {processed_count} rows into batch {batch.id}"
        if skipped_nsfw:
            message += f" (skipped {skipped_nsfw} NSFW rows)"
        self.stdout.write(self.style.SUCCESS(message))

    def _resolve_ingested_date(self, csv_path: Path, override: str | None) -> date:
        if override:
            try:
                return datetime.strptime(override, "%Y-%m-%d").date()
            except ValueError as exc:
                raise CommandError(f"Invalid --ingested-date value: {override}") from exc

        # Try to infer from filename, e.g. new_games_2025-08-21.csv
        stem = csv_path.stem
        for token in stem.split("_"):
            try:
                return datetime.strptime(token, "%Y-%m-%d").date()
            except ValueError:
                continue
        return date.today()

    def _ingest_rows(self, batch: models.DiscoveryBatch, rows: list[dict[str, Any]]) -> tuple[int, int]:
        processed_count = 0
        skipped_nsfw = 0
        for row in rows:
            steam_appid = row.get("steam_appid")
            if not steam_appid:
                continue

            try:
                steam_id = int(steam_appid)
            except (TypeError, ValueError):
                self.stdout.write(self.style.WARNING(f"Skipping invalid appid: {steam_appid}"))
                continue

            is_nsfw, reasons = classify_nsfw_from_row(row)
            if is_nsfw:
                skipped_nsfw += 1
                reason_text = ", ".join(reasons)
                self.stdout.write(
                    self.style.WARNING(f"Skipping NSFW app {steam_appid}: {row.get('name', '').strip()} [{reason_text}]")
                )
                continue

            game, _ = models.Game.objects.get_or_create(
                steam_appid=steam_id,
                defaults={
                    "name": row.get("name", "").strip() or f"App {steam_appid}",
                    "steam_url": row.get("steam_url", ""),
                },
            )

            # Update canonical fields with latest data
            game.name = row.get("name", game.name) or game.name
            game.steam_url = row.get("steam_url", game.steam_url)
            game.website = row.get("website", game.website or "")
            game.developers = row.get("developers", game.developers or "")
            game.publishers = row.get("publishers", game.publishers or "")
            game.categories = row.get("categories", game.categories or "")
            game.genres = row.get("genres", game.genres or "")
            tag_value = row.get("target_tags_found") or row.get("tag_category") or game.tags or ""
            game.tags = tag_value
            game.latest_release_date = row.get("release_date", game.latest_release_date or "")
            game.latest_detection_stage = row.get("detection_stage", game.latest_detection_stage or "")
            game.latest_api_response_type = row.get("api_response_type", game.latest_api_response_type or "")
            assets = self._get_game_assets(steam_id, game)
            if assets.get("capsule"):
                game.capsule_image_url = assets["capsule"]
            if assets.get("header"):
                game.header_image_url = assets["header"]
            if assets.get("background"):
                game.background_image_url = assets["background"]
            if assets.get("screenshots"):
                game.screenshot_urls = assets["screenshots"]
            if assets.get("trailers"):
                game.trailer_videos = assets["trailers"]
            game.save()

            defaults = {
                "batch": batch,
                "detection_stage": row.get("detection_stage", ""),
                "api_response_type": row.get("api_response_type", ""),
                "potential_duplicate": str(row.get("potential_duplicate", "")).lower() in {"true", "1", "yes"},
                "discovery_date": self._parse_date(row.get("discovery_date")),
                "release_date_raw": row.get("release_date", ""),
                "description": row.get("description", ""),
                "supported_languages": row.get("supported_languages", ""),
                "followers": self._parse_int(row.get("followers")),
                "wishlists_est": self._parse_int(row.get("wishlists_est")),
                "wishlist_rank": self._parse_int(row.get("wishlist_rank")),
                "source_categories": row.get("categories", ""),
                "source_genres": row.get("genres", ""),
                "source_tags": row.get("target_tags_found", ""),
                "raw_payload": row,
            }

            models.GameSnapshot.objects.update_or_create(
                game=game,
                ingested_for_date=batch.ingested_for_date,
                defaults=defaults,
            )
            processed_count += 1

        return processed_count, skipped_nsfw

    def _parse_int(self, value: Any) -> int | None:
        if value in (None, "", "None"):
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    def _parse_date(self, value: str | None):
        if not value:
            return None
        for fmt in ("%Y-%m-%d", "%Y/%m/%d"):
            try:
                return datetime.strptime(value, fmt).date()
            except ValueError:
                continue
        return None

    def _get_game_assets(self, appid: int, game: models.Game) -> dict[str, object]:
        # Prefer existing values to avoid unnecessary requests when everything is already populated
        has_core_images = bool(game.capsule_image_url and game.header_image_url and game.background_image_url)
        has_screenshots = bool(game.screenshot_urls)
        has_trailers = bool(getattr(game, "trailer_videos", []))
        if has_core_images and has_screenshots and has_trailers:
            return {
                "capsule": game.capsule_image_url,
                "header": game.header_image_url,
                "background": game.background_image_url,
                "screenshots": list(game.screenshot_urls or []),
                "trailers": list(getattr(game, "trailer_videos", []) or []),
            }

        if appid in self._asset_cache:
            return self._asset_cache[appid]

        assets: dict[str, object] = {}
        if game.capsule_image_url:
            assets["capsule"] = game.capsule_image_url
        if game.header_image_url:
            assets["header"] = game.header_image_url
        if game.background_image_url:
            assets["background"] = game.background_image_url
        if game.screenshot_urls:
            assets["screenshots"] = list(game.screenshot_urls)
        if getattr(game, "trailer_videos", []):
            assets["trailers"] = list(getattr(game, "trailer_videos", []))

        try:
            response = requests.get(
                "https://store.steampowered.com/api/appdetails",
                params={"appids": appid, "l": "en", "cc": "us"},
                timeout=6,
            )
            payload = response.json()
        except (requests.RequestException, ValueError):
            payload = None

        if isinstance(payload, dict):
            entry = payload.get(str(appid))
            if isinstance(entry, dict) and entry.get("success") and isinstance(entry.get("data"), dict):
                data = entry["data"]
                capsule = data.get("capsule_image") or data.get("capsule_imagev5")
                header = data.get("header_image")
                background = data.get("background_raw") or data.get("background")
                screenshots = []
                for screenshot in data.get("screenshots", []) or []:
                    if isinstance(screenshot, dict):
                        url = screenshot.get("path_full") or screenshot.get("path_thumbnail")
                        if url:
                            screenshots.append(url)
                    if len(screenshots) >= 8:
                        break
                if capsule:
                    assets["capsule"] = capsule
                if header:
                    assets["header"] = header
                if background:
                    assets["background"] = background
                if screenshots:
                    assets["screenshots"] = screenshots
                trailers = []
                for movie in data.get("movies", []) or []:
                    if not isinstance(movie, dict):
                        continue
                    mp4_data = movie.get("mp4") or {}
                    webm_data = movie.get("webm") or {}
                    mp4_url = mp4_data.get("max") or mp4_data.get("480")
                    webm_url = webm_data.get("max") or webm_data.get("480")
                    if not (mp4_url or webm_url):
                        continue
                    trailers.append(
                        {
                            "id": movie.get("id"),
                            "name": movie.get("name"),
                            "thumbnail": movie.get("thumbnail"),
                            "mp4": mp4_url,
                            "webm": webm_url,
                            "highlight": bool(movie.get("highlight")),
                        }
                    )
                if trailers:
                    assets["trailers"] = trailers

        self._asset_cache[appid] = assets
        return assets
