# Generated by Django 5.2.7 on 2025-10-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistMomentum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "window",
                    models.CharField(
                        choices=[("3d", "3 days"), ("7d", "7 days")], max_length=8
                    ),
                ),
                (
                    "calc_date",
                    models.DateField(
                        help_text="Business date the metric was calculated for."
                    ),
                ),
                (
                    "baseline_value",
                    models.IntegerField(
                        help_text="Baseline wishlist/follower value at window start."
                    ),
                ),
                ("latest_followers", models.IntegerField(blank=True, null=True)),
                ("latest_wishlists_est", models.IntegerField(blank=True, null=True)),
                (
                    "delta_followers",
                    models.IntegerField(
                        help_text="Net follower change within the window."
                    ),
                ),
                (
                    "delta_per_day",
                    models.FloatField(help_text="Average follower change per day."),
                ),
                (
                    "delta_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Relative change against baseline.",
                        null=True,
                    ),
                ),
                (
                    "percentile",
                    models.FloatField(
                        blank=True,
                        help_text="Percentile ranking within the peer group.",
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Rank within the window for calc_date (1 = fastest growth)."
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="momentum_entries",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-calc_date", "window", "rank"],
                "indexes": [
                    models.Index(
                        fields=["calc_date", "window"],
                        name="core_wishli_calc_da_d721ee_idx",
                    ),
                    models.Index(
                        fields=["window", "rank"], name="core_wishli_window_71bb34_idx"
                    ),
                ],
                "unique_together": {("game", "window", "calc_date")},
            },
        ),
    ]
