# Generated by Django 5.2.7 on 2025-10-24 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_dailygameengagement"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailygameengagement",
            new_name="core_dailyg_summary_0a7b62_idx",
            old_name="core_daily_summary_84f7ba_idx",
        ),
        migrations.RenameIndex(
            model_name="dailygameengagement",
            new_name="core_dailyg_summary_fa2e82_idx",
            old_name="core_daily_summary_416ca5_idx",
        ),
    ]
