# Generated by Django 5.2.7 on 2025-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0004_rename_core_daily_summary_84f7ba_idx_core_dailyg_summary_0a7b62_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="background_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="game",
            name="capsule_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="game",
            name="header_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
