# Generated by Django 5.2.7 on 2025-10-26 22:10

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_gamesnapshots(apps, schema_editor):
    GameSnapshot = apps.get_model("core", "GameSnapshot")
    duplicates = (
        GameSnapshot.objects.values("game_id", "ingested_for_date")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for entry in duplicates:
        qs = (
            GameSnapshot.objects.filter(
                game_id=entry["game_id"], ingested_for_date=entry["ingested_for_date"]
            )
            .order_by("-created_at", "-id")
        )
        keep = qs.first()
        if keep:
            qs.exclude(pk=keep.pk).delete()


def dedupe_swipeactions(apps, schema_editor):
    SwipeAction = apps.get_model("core", "SwipeAction")
    duplicates = (
        SwipeAction.objects.values("user_id", "game_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for entry in duplicates:
        qs = (
            SwipeAction.objects.filter(user_id=entry["user_id"], game_id=entry["game_id"])
            .order_by("-created_at", "-id")
        )
        keep = qs.first()
        if keep:
            qs.exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_game_background_image_url_game_capsule_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_gamesnapshots, migrations.RunPython.noop),
        migrations.RunPython(dedupe_swipeactions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="gamesnapshot",
            constraint=models.UniqueConstraint(
                fields=("game", "ingested_for_date"),
                name="unique_game_snapshot_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="swipeaction",
            constraint=models.UniqueConstraint(
                fields=("user", "game"), name="unique_user_game_swipe"
            ),
        ),
    ]
