# Generated by Django 5.2.7 on 2025-10-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_gamesnapshot_unique_game_snapshot_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="screenshot_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
