# Generated by Django 5.2.7 on 2025-10-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_game_screenshot_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="trailer_videos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
